[package]
name = "keypair"
version = "0.0.1"
edition = "2021"

[dependencies]
ed25519-dalek = { version = "2.1.0", features = ["rand_core"] }
rand = { version = "0.8.5" }

[dev-dependencies]
rand = { version = "0.8.5" }